version: '3.8'

services:
  # Combined Ollama + FastAPI service
  web:
    build:
      context: .
      dockerfile: Dockerfile
    # Mount just your source and env for local dev
    volumes:
      - ./src:/app/src:rw
      - ./.env:/app/.env:ro
    ports:
      - "11434:11434"
      - "8080:8080"
    depends_on:
      - mongodb
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app/src

  # MongoDB database service
  mongodb:
    image: mongo:6.0
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo_data: