version: '3.8'

services:
  app:
    build: .
    container_name: customer_support_bot
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - DATABASE_NAME=mj-mongo-db
      - META_COLLECTION=customer-support-meta
      - EMBEDDINGS_COLLECTION=customer-support-embeddings
      - EMBEDDING_MODEL=hf.co/CompendiumLabs/bge-base-en-v1.5-gguf
      - LANGUAGE_MODEL=hf.co/bartowski/Llama-3.2-1B-Instruct-GGUF
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - mongodb
    ports:
      - "5000:5000"  # Optional, only needed if your app exposes a port (e.g., for a web service)

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodb_data: